/*{"created":"2010-10-12T04:03:29Z","mac":"1:723b80f50b022bb081284358773ee0e7a72aa9920297a9c06aa333fa87078dae","k":"0.7.16","version":"973830"}*/
;(function(window,document,undefined){
function o(a){return function(){return this[a]}}var p;function q(a,b){this.q=a;this.i=b}p=q.prototype;p.createElement=function(a,b,c){a=this.q.createElement(a);if(b)for(var d in b)if(b.hasOwnProperty(d))if(d=="style"&&this.i.getName()=="MSIE")a.style.cssText=b[d];else a.setAttribute(d,b[d]);c&&a.appendChild(this.q.createTextNode(c));return a};p.insertInto=function(a,b){a=this.q.getElementsByTagName(a)[0];if(!a)a=document.documentElement;if(a&&a.lastChild){a.insertBefore(b,a.lastChild);return true}return false};
p.removeElement=function(a){if(a.parentNode){a.parentNode.removeChild(a);return true}return false};p.createCssLink=function(a){return this.createElement("link",{rel:"stylesheet",href:a})};p.appendClassName=function(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/^\s+/,"")};
p.removeClassName=function(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,h=c.length;e<h;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")};function r(a,b,c,d,e,h,j,g){this.ga=a;this.pa=b;this.aa=c;this.$=d;this.ja=e;this.ia=h;this.Z=j;this.qa=g}p=r.prototype;p.getName=o("ga");p.getVersion=o("pa");p.getEngine=o("aa");p.getEngineVersion=o("$");p.getPlatform=o("ja");p.getPlatformVersion=o("ia");p.getDocumentMode=o("Z");function s(a,b){this.i=a;this.t=b}
var aa=new r("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",undefined,false);s.prototype.parse=function(){return this.i.indexOf("MSIE")!=-1?ba(this):this.i.indexOf("Opera")!=-1?ca(this):this.i.indexOf("AppleWebKit")!=-1?da(this):this.i.indexOf("Gecko")!=-1?ea(this):aa};function t(a){var b=u(a,a.i,/(iPod|iPad|iPhone|Android)/,1);if(b!="")return b;a=u(a,a.i,/(Linux|Mac_PowerPC|Macintosh|Windows)/,1);if(a!=""){if(a=="Mac_PowerPC")a="Macintosh";return a}return"Unknown"}
function v(a){var b=u(a,a.i,/(OS X|Windows NT|Android) ([^;]+)/,2);if(b)return b;if(b=u(a,a.i,/(iPhone )?OS ([\d_]+)/,2))return b;if(a=u(a,a.i,/Linux ([i\d]+)/,1))return a;return"Unknown"}function ba(a){var b=u(a,a.i,/(MSIE [\d\w\.]+)/,1);if(b!=""){var c=b.split(" ");b=c[0];c=c[1];return new r(b,c,b,c,t(a),v(a),w(a,a.t),x(a,c)>=6)}return new r("MSIE","Unknown","MSIE","Unknown",t(a),v(a),w(a,a.t),false)}
function ca(a){var b="Unknown",c="Unknown",d=u(a,a.i,/(Presto\/[\d\w\.]+)/,1);if(d!=""){c=d.split("/");b=c[0];c=c[1]}else{if(a.i.indexOf("Gecko")!=-1)b="Gecko";d=u(a,a.i,/rv:([^\)]+)/,1);if(d!="")c=d}if(a.i.indexOf("Version/")!=-1){d=u(a,a.i,/Version\/([\d\.]+)/,1);if(d!="")return new r("Opera",d,b,c,t(a),v(a),w(a,a.t),x(a,d)>=10)}d=u(a,a.i,/Opera[\/ ]([\d\.]+)/,1);if(d!="")return new r("Opera",d,b,c,t(a),v(a),w(a,a.t),x(a,d)>=10);return new r("Opera","Unknown",b,c,t(a),v(a),w(a,a.t),false)}
function da(a){var b=t(a),c=v(a),d=u(a,a.i,/AppleWebKit\/([\d\.\+]+)/,1);if(d=="")d="Unknown";var e="Unknown";if(a.i.indexOf("Chrome")!=-1)e="Chrome";else if(a.i.indexOf("Safari")!=-1)e="Safari";var h="Unknown";if(a.i.indexOf("Version/")!=-1)h=u(a,a.i,/Version\/([\d\.\w]+)/,1);else if(e=="Chrome")h=u(a,a.i,/Chrome\/([\d\.]+)/,1);var j=u(a,d,/\d+\.(\d+)/,1);return new r(e,h,"AppleWebKit",d,b,c,w(a,a.t),x(a,d)>=526||x(a,d)>=525&&parseInt(j,10)>=13)}
function ea(a){var b="Unknown",c="Unknown",d=false;if(a.i.indexOf("Firefox")!=-1){b="Firefox";var e=u(a,a.i,/Firefox\/([\d\w\.]+)/,1);if(e!=""){d=u(a,e,/\d+\.(\d+)/,1);c=e;d=e!=""&&x(a,e)>=3&&parseInt(d,10)>=5}}else if(a.i.indexOf("Mozilla")!=-1)b="Mozilla";e=u(a,a.i,/rv:([^\)]+)/,1);if(e=="")e="Unknown";else if(!d){d=x(a,e);var h=parseInt(u(a,e,/\d+\.(\d+)/,1),10),j=parseInt(u(a,e,/\d+\.\d+\.(\d+)/,1),10);d=d>1||d==1&&h>9||d==1&&h==9&&j>=2||e.match(/1\.9\.1b[123]/)!=null||e.match(/1\.9\.1\.[\d\.]+/)!=
null}return new r(b,c,"Gecko",e,t(a),v(a),w(a,a.t),d)}function x(a,b){a=u(a,b,/(\d+)/,1);if(a!="")return parseInt(a,10);return-1}function u(a,b,c,d){if((a=b.match(c))&&a[d])return a[d];return""}function w(a,b){if(b.documentMode)return b.documentMode}function fa(a,b,c,d){this.j=a;this.m=b;this.L=c;this.p=d||ga;this.o=new y("-")}var ga="wf";function z(a,b,c){a.j.removeClassName(a.m,a.o.n(a.p,b,c,"loading"));a.j.appendClassName(a.m,a.o.n(a.p,b,c,"active"));A(a,"fontactive",b,c)}
function B(a){a.j.removeClassName(a.m,a.o.n(a.p,"loading"));a.j.appendClassName(a.m,a.o.n(a.p,"inactive"));A(a,"inactive")}function ha(a){a.j.removeClassName(a.m,a.o.n(a.p,"loading"));a.j.appendClassName(a.m,a.o.n(a.p,"active"));A(a,"active")}function A(a,b,c,d){a.L[b]&&a.L[b](c,d)}function D(a,b,c,d,e){this.j=a;this.v=b;this.G=c;this.r=d;this.Q=e;this.M=0;this.J=this.T=false;this.fa=new E;this.ba=new F}
D.prototype.watch=function(a,b,c){for(var d=a.length,e=0;e<d;e++){var h=a[e];b[h]||(b[h]=["n4"]);this.M+=b[h].length}if(c)this.T=c;for(e=0;e<d;e++){h=a[e];c=b[h];for(var j=0,g=c.length;j<g;j++){var f=c[j],i=G(this,"_,arial,helvetica",f),l=this.G.H(i);this.j.removeElement(i);i=h;var n=this.v;n.j.appendClassName(n.m,n.o.n(n.p,i,f,"loading"));A(n,"fontloading",i,f);n=G(this,this.fa.quote(i),f);if(l!=this.G.H(n)){this.j.removeElement(n);z(this.v,i,f);this.J=true;H(this)}else I(this,this.Q(),l,n,i,f)}}};
function H(a){if(--a.M==0&&a.T)a.J?ha(a.v):B(a.v)}D.prototype.Y=function(a,b,c,d,e){if(b!=this.G.H(c)){this.j.removeElement(c);z(this.v,d,e);this.J=true;H(this)}else if(this.Q()-a<5E3)I(this,a,b,c,d,e);else{this.j.removeElement(c);a=this.v;a.j.removeClassName(a.m,a.o.n(a.p,d,e,"loading"));a.j.appendClassName(a.m,a.o.n(a.p,d,e,"inactive"));A(a,"fontinactive",d,e);H(this)}};function I(a,b,c,d,e,h){a.r(function(j,g){return function(){g.call(j,b,c,d,e,h)}}(a,a.Y),50)}
function G(a,b,c){c=a.ba.expand(c);b=a.j.createElement("span",{style:"position:absolute;top:-999px;font-size:300px;font-family:"+b+",_,arial,helvetica;"+c},"Mm");a.j.insertInto("body",b);return b}function y(a){this.da=a||ia}var ia="-";y.prototype.n=function(){for(var a=[],b=0;b<arguments.length;b++)a.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return a.join(this.da)};function E(){this.W='"'}
E.prototype.quote=function(a){var b=[];a=a.split(/,\s*/);for(var c=0;c<a.length;c++){var d=a[c].replace(/['"]/g,"");d.indexOf(" ")==-1?b.push(d):b.push(this.W+d+this.W)}return b.join(",")};function F(){this.V=ja;this.z=ka}var ja=["font-style","font-weight"],ka={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function J(a,b,c){this.ca=a;this.ka=b;this.z=c}J.prototype.expand=function(a,b){for(var c=0;c<this.z.length;c++)if(b==this.z[c][0]){a[this.ca]=this.ka+":"+this.z[c][1];return}};F.prototype.expand=function(a){if(a.length!=2)return null;for(var b=[null,null],c=0,d=this.V.length;c<d;c++){var e=this.V[c],h=a.substr(c,1);(new J(c,e,this.z[e])).expand(b,h)}return b[0]&&b[1]?b.join(";")+";":null};function K(a,b){this.q=a;this.i=b}K.prototype=q.prototype;
K.prototype.isHttps=function(){return this.q.location.protocol=="https:"};K.prototype.loadScript=function(a,b){var c=this.q.getElementsByTagName("head")[0];if(c){var d=this.q.createElement("script");d.src=a;var e=false;d.onload=d.onreadystatechange=function(){if(!e&&(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")){e=true;b&&b();d.onload=d.onreadystatechange=null;d.parentNode.tagName=="HEAD"&&c.removeChild(d)}};c.appendChild(d)}};
K.prototype.createStyle=function(a){var b=this.q.createElement("style");b.setAttribute("type","text/css");if(b.styleSheet)b.styleSheet.cssText=a;else b.appendChild(document.createTextNode(a));return b};function L(a,b){this.na=a;this.N=b}function la(a){for(var b=a.na.join(","),c=[],d=0;d<a.N.length;d++){var e=a.N[d];c.push(e.name+":"+e.value+";")}return b+"{"+c.join("")+"}"}function M(a,b){this.B=a;this.O=b}
M.prototype.watch=function(a,b,c){var d=[],e={};d.push(this.B);e[this.B]=this.O[b.getStylesheetFormatId()]||[];a.watch(d,e,c)};function N(a,b,c){this.oa=a;this.I=b;this.la=c}N.prototype.buildUrl=function(a,b){a=this.oa&&a?"https:":"http:";var c=typeof this.I=="function"?this.I(a):this.I;return a+"//"+c+this.la+b};
function ma(a,b,c){if(a.P){var d=function(){try{b._gat._getTracker("UA-8850781-3")._trackPageview();b.tkKitsTracked||(b.tkKitsTracked=0);b.tkKitsTracked++}catch(e){}};if(b._gat)d();else{a=a.P.buildUrl(c.isHttps(),"/ga.js");c.loadScript(a,d)}}}function O(a,b,c){this.w=a;this.X=b;this.S=c}O.prototype.getId=o("w");O.prototype.getStylesheetFormatId=o("X");
O.prototype.isUserAgent=function(a){return this.S?this.S(a.getName(),a.getVersion(),a.getEngine(),a.getEngineVersion(),a.getPlatform(),a.getPlatformVersion(),a.getDocumentMode()):false};O.prototype.buildCssUrl=function(a,b,c,d){c="/"+c+"-"+this.X+".css";if(d)c+="?"+d;return b.buildUrl(a,c)};function P(){this.s=[]}P.prototype.k=function(a){Q(this,a.getId())||this.s.push(a)};function Q(a,b){for(var c=0;c<a.s.length;c++){var d=a.s[c];if(b===d.getId())return d}return null}
function R(a,b){for(var c=0;c<a.s.length;c++){var d=a.s[c];if(d.isUserAgent(b))return d}return null}P.prototype.addBrowsersToBrowserSet=function(a){for(var b=0;b<this.s.length;b++)a.k(this.s[b])};function S(a){this.w=a;this.F=new P;this.u=[];this.A=[]}p=S.prototype;p.getId=o("w");p.k=function(a){this.F.k(a)};p.supportsBrowser=function(a){return!!Q(this.F,a.getId())};p.addBrowsersToBrowserSet=function(a){this.F.addBrowsersToBrowserSet(a)};
p.init=function(a){for(var b=[],c=0;c<this.A.length;c++)b.push(la(this.A[c]));a.insertInto("head",a.createStyle(b.join("")))};p.load=function(a,b,c,d,e){var h=c.buildCssUrl(a.isHttps(),this.ha,this.w,this.ma);a.insertInto("head",a.createCssLink(h));b&&d(function(j,g,f,i){return function(){for(var l=0;l<j.u.length;l++)j.u[l].watch(g,f,i&&l==j.u.length-1)}}(this,b,c,e))};
p.performOptionalActions=function(a,b,c,d){this.C&&d(function(e,h,j,g){return function(){ma(e.C,h,g);var f=e.C,i=e.w;if(f.U){f=f.U.buildUrl(g.isHttps(),"/"+i+".js?"+ +new Date);g.loadScript(f)}i=e.C;f=e.w;if(i.K){i=i.K.n(f,j,g);i.setAttribute("id","typekit-badge-"+f);g.insertInto("body",i)}}}(this,a,b,c))};function T(a,b,c,d,e){this.ea=a;this.j=b;this.i=c;this.m=d;this.r=e;this.l=[]}T.prototype.D=function(a){this.l.push(a)};
T.prototype.load=function(a,b){a=a;var c=b||{};if(typeof a=="string")a=[a];else if(a&&a.length)a=a;else{c=a||{};a=[]}if(a.length){var d=this,e=a.length;for(b=0;b<a.length;b++)na(this,a[b],function(){--e==0&&U(d,c)})}else U(this,c)};function na(a,b,c){a.j.loadScript(a.ea.buildUrl(a.j.isHttps(),"/"+b+".js"),c)}
function U(a,b){if(b.userAgent)a.i=(new s(b.userAgent,document)).parse();b=new fa(a.j,a.m,b);for(var c=new P,d=0;d<a.l.length;d++)a.l[d].addBrowsersToBrowserSet(c);c=R(c,a.i);for(d=0;d<a.l.length;d++)a.l[d].init(a.j);if(c){b.j.appendClassName(b.m,b.o.n(b.p,"loading"));A(b,"loading");oa(a,c,b)}else B(b);a.l=[]}
function oa(a,b,c){c=new D(a.j,c,{H:function(h){return h.offsetWidth}},a.r,function(){return+new Date});for(var d=0;d<a.l.length;d++){var e=a.l[d];if(e.supportsBrowser(b)){e.load(a.j,c,b,a.r,d==a.l.length-1);e.performOptionalActions(window,a.i,a.j,a.r)}}}function V(a,b,c){this.R=a;this.j=b;this.r=c;this.l=[]}V.prototype.D=function(a){this.l.push(a)};
V.prototype.load=function(){var a=this.R.__webfonttypekitmodule__;if(a)for(var b=0;b<this.l.length;b++){var c=this.l[b],d=a[c.getId()];if(d){var e=this.j,h=this.r;d(function(j,g,f){var i=new P;c.addBrowsersToBrowserSet(i);g=[];var l={};if(i=R(i,j)){c.init(e);c.load(e,null,i,h);for(var n=0;n<c.u.length;n++){var k=c.u[n];g.push(k.B);l[k.B]=k.O[i.getStylesheetFormatId()]||[]}c.performOptionalActions(window,j,e,h)}f(!!i,g,l)})}}};var W=new P;
W.k(new O("ie9-win7","g",function(a,b,c,d,e,h,j){var g=false;g=g||(e=="Windows"&&h=="6.1"?true:false);if(!g)return false;return function(f,i,l,n,k,m,C){if(f=="MSIE"){if(f=/([0-9]+.[0-9]+)/.exec(i))return parseFloat(f[1])>=9&&C>=9;return false}}(a,b,c,d,e,h,j)}));
W.k(new O("opera-linux-osx-win7-winvista-winxp","b",function(a,b,c,d,e,h,j){var g=false;g=(g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,i,l,n,k,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(k=="Macintosh"&&f){k=parseInt(f[1],10);m=parseInt(f[3],10);if(k==10)return m>3;else if(k>10)return true}else return k=="Macintosh"&&m=="Unknown"?true:false}(a,b,c,d,e,h,j))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;
return a=="Opera"?parseFloat(b)>=10.54:false}));W.k(new O("ie9-winvista","h",function(a,b,c,d,e,h,j){var g=false;g=g||(e=="Windows"&&h=="6.0"?true:false);if(!g)return false;return function(f,i,l,n,k,m,C){if(f=="MSIE"){if(f=/([0-9]+.[0-9]+)/.exec(i))return parseFloat(f[1])>=9&&C>=9;return false}}(a,b,c,d,e,h,j)}));
W.k(new O("ie-win7-winvista-winxp","c",function(a,b,c,d,e,h,j){var g=false;g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false);if(!g)return false;return function(f,i,l,n,k,m,C){if(f=="MSIE"){if(f=/([0-9]+.[0-9]+)/.exec(i))return parseFloat(f[1])>=6&&(C===undefined||C<9);return false}}(a,b,c,d,e,h,j)}));
W.k(new O("ff35-linux-osx-win7-winvista-winxp","b",function(a,b,c,d,e,h,j){var g=false;g=(g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,i,l,n,k,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(k=="Macintosh"&&f){k=parseInt(f[1],10);m=parseInt(f[3],10);if(k==10)return m>3;else if(k>10)return true}else return k=="Macintosh"&&m=="Unknown"?true:false}(a,b,c,d,e,h,j))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;
return function(f,i,l,n){if(l=="Gecko"){f=/1.9.1b[1-3]{1}/;return/1.9.1/.test(n)&&!f.test(n)}return false}(a,b,c,d,e,h,j)}));
W.k(new O("safari-osx-win7-winvista-winxp","b",function(a,b,c,d,e,h,j){var g=false;g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,i,l,n,k,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(k=="Macintosh"&&f){k=parseInt(f[1],10);m=parseInt(f[3],10);if(k==10)return m>3;else if(k>10)return true}else return k=="Macintosh"&&m=="Unknown"?true:false}(a,b,c,d,e,h,j);if(!g)return false;return function(f,i,l,n){if(f=="Safari"&&
l=="AppleWebKit")if(f=/([0-9]+.[0-9]+)/.exec(n))return parseFloat(f[1])>=525.13;return false}(a,b,c,d,e,h,j)}));W.k(new O("chrome6-win7-winvista-winxp","e",function(a,b,c,d,e,h,j){var g=false;g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false);if(!g)return false;return function(f,i){if(f=="Chrome")if(f=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(i))if(parseFloat(f[1])>=6)return true}(a,b,c,d,e,h,j)}));
W.k(new O("safari-android","a",function(a,b,c,d,e,h,j){var g=false;g=g||function(f,i,l,n,k,m){f=/([0-9]+).([0-9]+)/.exec(m);if(k=="Android"&&f){k=parseInt(f[1]);f=parseInt(f[2]);return k>2||k==2&&f>=2}else return false}(a,b,c,d,e,h,j);if(!g)return false;return function(f,i,l,n){if(f=="Safari"&&l=="AppleWebKit")if(f=/([0-9]+.[0-9]+)/.exec(n))return parseFloat(f[1])>=525.13;return false}(a,b,c,d,e,h,j)}));
W.k(new O("chrome-linux-osx-win7-winvista-winxp","b",function(a,b,c,d,e,h,j){var g=false;g=(g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,i,l,n,k,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(k=="Macintosh"&&f){k=parseInt(f[1],10);m=parseInt(f[3],10);if(k==10)return m>3;else if(k>10)return true}else return k=="Macintosh"&&m=="Unknown"?true:false}(a,b,c,d,e,h,j))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;
return function(f,i){if(f=="Chrome"){var l=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(i);if(l){f=parseFloat(l[1]);i=parseInt(l[2],10);l=parseInt(l[3],10);if(f>=6)return false;else if(f>4)return true;else if(f==4&&i>249)return true;else if(f==4&&i==249&&l>=4)return true}}return false}(a,b,c,d,e,h,j)}));
W.k(new O("chrome6-linux-osx","d",function(a,b,c,d,e,h,j){var g=false;g=(g=g||function(f,i,l,n,k,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(k=="Macintosh"&&f){k=parseInt(f[1],10);m=parseInt(f[3],10);if(k==10)return m>3;else if(k>10)return true}else return k=="Macintosh"&&m=="Unknown"?true:false}(a,b,c,d,e,h,j))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;return function(f,i){if(f=="Chrome")if(f=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(i))if(parseFloat(f[1])>=6)return true}(a,b,c,d,e,h,
j)}));
W.k(new O("ff36-linux-osx-win7-winvista-winxp","e",function(a,b,c,d,e,h,j){var g=false;g=(g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,i,l,n,k,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(k=="Macintosh"&&f){k=parseInt(f[1],10);m=parseInt(f[3],10);if(k==10)return m>3;else if(k>10)return true}else return k=="Macintosh"&&m=="Unknown"?true:false}(a,b,c,d,e,h,j))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;return function(f,
i,l,n){if(l=="Gecko")if(i=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(n)){f=parseFloat(i[1]);i=parseInt(i[3],10);return f>1.9||f>=1.9&&i>1}return false}(a,b,c,d,e,h,j)}));if(!window.Typekit){var pa=new N(false,"use.typekit.com","/"),X=(new s(navigator.userAgent,document)).parse(),qa=new K(document,X),ra=function(a,b){setTimeout(a,b)},Y=new T(pa,qa,X,document.documentElement,ra),Z=new V(window,qa,ra);window.Typekit=Y;window.Typekit.load=Y.load;window.Typekit.addKit=Y.D}var sa,ta=null,ua,$;
sa=new N(false,"use.typekit.com","/k");ta=new N(false,function(a){return(a=="https:"?"ssl":"www")+".google-analytics.com"},"");ua=new function(a,b,c){this.K=a;this.P=b;this.U=c}(null,ta,null);$=new S("oxp7sai");$.ma="3bb2a6e53c9684ffdc9a9bf6185b2a629cf3c5837407c6052dad8c7a2a550071ad0e106034bc36bc1f8f0ce85a6ca6a0b50caed6eda4faedc828f344a36da6b45619350d814af0450047a098e2c13c25fb1b9ee31cbd35c2ef4f522fb1e7c312a0ff407eecf8";$.ha=sa;$.C=ua;
$.u.push(new M('"pill-gothic-600mg-1","pill-gothic-600mg-2"',{a:["n4"],b:["n4"],c:["n4"],d:["n4"],e:["n4"],f:["n4"],g:["n4"],h:["n4"]}));$.u.push(new M('"pill-gothic-300mg-1","pill-gothic-300mg-2"',{a:["n4"],b:["n4"],c:["n4"],d:["n4"],e:["n4"],f:["n4"],g:["n4"],h:["n4"]}));$.A.push(new L([".warning","header"],[{value:'"pill-gothic-600mg-1","pill-gothic-600mg-2",sans-serif',name:"font-family"}]));$.A.push(new L(["#web"],[{value:'"pill-gothic-300mg-1","pill-gothic-300mg-2",sans-serif',name:"font-family"}]));
$.k(Q(W,"chrome-linux-osx-win7-winvista-winxp"));$.k(Q(W,"chrome6-linux-osx"));$.k(Q(W,"chrome6-win7-winvista-winxp"));$.k(Q(W,"ff35-linux-osx-win7-winvista-winxp"));$.k(Q(W,"ff36-linux-osx-win7-winvista-winxp"));$.k(Q(W,"ie-win7-winvista-winxp"));$.k(Q(W,"ie9-win7"));$.k(Q(W,"ie9-winvista"));$.k(Q(W,"opera-linux-osx-win7-winvista-winxp"));$.k(Q(W,"safari-android"));$.k(Q(W,"safari-osx-win7-winvista-winxp"));if(Z&&Z.R.__webfonttypekitmodule__){Z.D($);Z.load()}else window.Typekit.addKit($);
})(this,document);
window.Typekit.config={"p":"//p.typekit.net/p.gif?s=1&k=oxp7sai&ht=tk&h={host}&f=630.622&a=11413&_={_}"};
/*{"created":"2012-08-06T22:41:05Z","mac":"1:87e372f470357348a98546f4f6196a4d46f6a130ad53e4766b712c28098ab951","k":"1.0.0"}*/
;(function(window,document,undefined){
function e(a){this.a=a}e.prototype=function(a){this.a=a}.prototype;function f(a){var b=new Image(1,1);b.src=a;b.onload=function(){b.onload=null}}function g(){this.c=window.Typekit.config.p}function h(a,b,c){var d=c||{},a=a.c.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,c){return c&&d[b]?"/"+d[b].join("/"):d[b]||""});a.match(/^\/\//)&&(a=(b?"https:":"http:")+a);return a.replace(/\/*\?*($|\?)/,"$1")}window.Typekit||(window.Typekit={});var i=new e(document),j=new function(){this.b=new g},k=!1;
function l(){if(!k)for(var a=document.getElementsByTagName("link"),b=0;b<a.length;b++){var c=a[b].getAttribute("href");if(c&&0<=c.indexOf("use.typekit")){a=j;b=i;a.b&&(c=(c=window.__adobewebfontsappname__)?c.toString().substr(0,20):"",f(h(a.b,"https:"==b.a.location.protocol,{host:encodeURIComponent(b.a.location.hostname),app:encodeURIComponent(c),_:(+new Date).toString()})));k=!0;break}}}var m=window.Typekit.load;window.Typekit.load=function(){m&&m.apply(window.Typekit,arguments);l()};
window.__webfonttypekitmodule__&&l();
})(this,document);